name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: docker build . -t check-python-version

      - run: |
          mkdir foobar
          echo "VERSION = '1.0a1'" > foobar/version.py

      - run: >
          docker run --rm
          -e INPUT_VERSION_FILE_PATH
          -e GITHUB_RER
          -v `pwd`:/app
          check-python-version
        id: check-python-version
        env:
          GITHUB_REF: refs/tags/v1.0.0a1
          INPUT_VERSION_FILE_PATH: foobar/version.py

      - run: steps.check-python-version.outputs.IS_PRERELEASE == 'true'
      - run: steps.check-python-version.outputs.VERSION == '1.0a1'

  test-action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir foobar
          echo "__version__ = 'v1.0post1'" > mypackage/version.py

      - uses: samuelcolvin/check-python-version@main
        id: check-python-version
        with:
          version_file_path: mypackage/version.py
        env:
          GITHUB_REF: refs/tags/1-post1

      - run: steps.check-python-version.outputs.IS_PRERELEASE == 'false'
      - run: steps.check-python-version.outputs.VERSION == '1.0post1'
